### ISSUE TITLE
Test Execution starts failing after few hours on iOS 11 devices

### ISSUE THREAD

**Issue by skhand001** [calabash/calabash-ios#1336]
On iOS 11 devices, test execution stops after around 100 scenarios.
Gems being used - 
run_loop - 2.6.1
calabash-cucumber - 0.21.1
cucumber - 3.0.0.pre.2

All tests fail with the message - 

Could not install /Users/skhand003c/.rvm/gems/ruby-2.3.1@test_mobile/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:

Error getting device with ID 0b24f5e627432391c2990de27d2d185296671dc6: Error Domain=com.facebook.FBDeviceControl Code=0 "Failed to create HUB control channel" UserInfo={NSLocalizedDescription=Failed to create HUB control channel}

**Comment by skhand001** [comment]
@jmoody Can you please suggest any ideas in debugging this further?

**Comment by jmoody** [comment]
Just back from vacation.

I have no suggestions.

Captured in our internal tracker.

https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/24505

**Comment by sivaramprasadc** [comment]
We are also facing same issue when ran command start_test_server_in_background
Device with iOS 11
Xcode 9

**Comment by TheChell** [comment]
Facing this issue here as well. We've tried multiple devices and versions of Xcode, currently running

- iOS **11.0.3**
- Xcode **9.0**
- run_loop **2.6.1**
- calabash-cucumber **0.20.4**

Have also seen this with iOS 9. The jobs we're running seem to time out around 3 hours. Rebooting the device resolves the issue, but this causes all nightly runs to fail until a manual restart has been done.

**Comment by otamas94** [comment]
Facing the issue as well on two devices, but for me it's:

- iOS 9.3.2 and 10.3.2

- XCode 8.3.3

- run_loop 2.4.1

- calabash-cucumber 0.20.5,

After 2 hours of execution all the tests are starting to fail first with these error on iOS9:

` Could not connect to the DeviceAgent service.
10:36:37   
10:36:37   device: #<Device: mactester’s iPhone (9.3.2) 63f2eaa6db82206b6e7cb34548005a07b09f22b7>
10:36:37      url: http://192.168.3.85:27753/
10:36:37   
10:36:37   To diagnose the problem tail the launcher log file:
10:36:37   
10:36:37   $ tail -1000 -F /Users/autotest/.calabash/iOSDeviceManager/logs/current.log`

On iOS10 for the first time it fails with this, and on iOS 9 after the first one all of the others fail with the same error like in the comments above:

`Could not install /usr/local/lib/ruby/gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:
10:39:08  
10:39:08  Error getting device with ID 63f2eaa6db82206b6e7cb34548005a07b09f22b7: (null)
10:39:08  
10:39:08  	install <device_id> <app_id> <profile_path> <codesign_id> <resign_object>
10:39:08  		-d,--device-id	<device-identifier> [OPTIONAL] 	iOS Simulator GUIDs
10:39:08  		-a,--app-path	<path/to/app-bundle.app or path/to/app.ipa>	Path .app bundle or .ipa
10:39:08  		-u,--update-app	<true-or-false> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1
10:39:08  		-p,--profile-path	<path/to/profile.mobileprovision> [OPTIONAL] 	Path to provisioning profile
10:39:08  		-c,--codesign-identity	<codesign-identity> [OPTIONAL] 	Identity used to codesign app bundle [device only]. Deprecated - should use profile path.	DEFAULT=
10:39:08  
10:39:08   (RuntimeError)
10:39:08  ./features/support/01_launch.rb:102:in `Before'`

**Comment by TheChell** [comment]
Saw the same with iOS 9. I think that iOS 11 has improved logging, which is why we're only seeing

`Error Domain=com.facebook.FBDeviceControl Code=0 "Failed to create HUB control channel" UserInfo={NSLocalizedDescription=Failed to create HUB control channel}`

there.

**Comment by otamas94** [comment]
We found a solution to handle the situation in a short time:
After every 20 tests we restart the devices via libimobiledevice's `idevicediagnostics restart` command. We put SIM cards in the phones to disable "No SIM card" message and put them into airplane mode to disable the "Service unavailable" message. After that we just needed a script to split the test set into several parts via autogenerated tags, and then only start the test with the generated tags, like @regression1 and @regression2 and etc. In that way we managed to have a fully successful evening run even with this issue.

**Comment by jmoody** [comment]
Possibly fixed in run-loop 2.6.2

Thanks for reporting.

Thanks for your patience.

**Comment by skhand001** [comment]
Tested with run_loop 2.6.2 - Issue is still there. Tried on iPhone 8 & iPhone X

**Comment by abardallis** [comment]
@jmoody I'm still seeing this issue as well across all our iOS devices.

ruby 2.3.4
run_loop 2.6.4
calabash-cucumber 0.21.2
Xcode 9.2
iOS 10.3.1, 11.0, 11.0.3, 11.1, 11.2


```
Scenario: verify existence of welcome page elements # features/welcome.feature:16
 
 
 Could not install /Users/{my_user_account}/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:
 
 Error getting device with ID 6523d786a05ebb78859c1930047ce46a09cb90a4: Error Domain=com.facebook.FBDeviceControl Code=0 "Failed to create HUB control channel" UserInfo={NSLocalizedDescription=Failed to create HUB control channel}
 
 	install <app-path>
 		-d,--device-id	<device-identifier>	iOS Simulator GUID or 40-digit physical device ID
 		-u,--update-app	<should-update-app> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1
 		-p,--profile-path	<profile-path> [OPTIONAL] 	Path to provisioning profile
 		-c,--codesign-identity	<codesign-identifier> [OPTIONAL] 	Identity used to codesign app bundle [device only]. Deprecated - should use profile path.	DEFAULT=
 		-i,--resources-path	<resources-path> [OPTIONAL] 	Path to resources (executables) to inject into app directory. A list of colon separated files may be specified.
 
  (RuntimeError)
 ./features/ios/support/app_life_cycle_hooks.rb:9:in `Before'
    Given I am on the welcome page                    # features/step_definitions/step_definitions.rb:2
    Then I can see the following elements             # features/step_definitions/step_definitions.rb:127
      | element                         |
      | gr_logo                         |
      | welcome_line_1_txt              |
      | welcome_line_2_txt              |
      | looking_for_registry_line_1_txt |
      | looking_for_registry_line_2_txt |
      | find_registry_btn               |
Retrying.. Errno::ECONNREFUSED: (Connection refused - Connection refused - connect(2) for "192.168.1.83" port 37265 (192.168.1.83:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - Connection refused - connect(2) for "192.168.1.83" port 37265 (192.168.1.83:37265))
Failing... Errno::ECONNREFUSED
      Connection refused - Connection refused - connect(2) for "192.168.1.83" port 37265 (192.168.1.83:37265) (Errno::ECONNREFUSED)
      ./features/ios/support/app_life_cycle_hooks.rb:20:in `After'

Failing Scenarios:
cucumber -p ios features/welcome.feature:16 # Scenario: verify existence of welcome page elements

1 scenario (1 failed)
2 steps (2 skipped)
0m12.838s

```




While the messaging is stating not being able to locate the device with the specified UDID, I did try multiple wifi networks that were working at one time, including my home network without any of the "corporate security junk" and still see the same issue (no surprise there). 

Hard reset of the device fixes the issue every time, and the regression test suite will run as normal. However, after a short time (usually by the time I leave work and the overnight runs start at 1:30am), the failures begin again.

**Comment by jmoody** [comment]
Reading the Xcode 9.3 beta release notes, I believe I saw a mention of this problem.

Basically, the connection with the device becomes unstable after testing for a long time.

Apple recommends breaking the tests into smaller chunks and restarting the device between chunks.

However, this troubles me:

```
 Could not install /Users/{my_user_account}/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.

iOSDeviceManager says:
 
 Error getting device with ID 6523d786a05ebb78859c1930047ce46a09cb90a4: Error Domain=com.facebook.FBDeviceControl Code=0 "Failed to create HUB control channel" UserInfo={NSLocalizedDescription=Failed to create HUB control channel}
```

Why is DeviceAgent not installed?  You say you are testing for many hours.  At some point DeviceAgent was installed.  Are you uninstalling DeviceAgent at some point?

**Comment by abardallis** [comment]
@jmoody thanks for the reply. I'm not uninstalling DeviceAgent at any point and looking at the device now, can see that DeviceAgent-Runner is still installed. 

I attempted the execution with `DEBUG` enabled and saw the same output as above preceded by the following:

`SHELL: xcrun simctl list devices --json`
`SHELL: xcrun instruments -s devices`
`DEBUG: HTTP: get http://192.168.1.83:27753/1.0/health {:retries=>1, :timeout=>0.5}`
`DEBUG: HTTP: get http://192.168.1.83:27753/1.0/health {:retries=>1, :timeout=>0.5}`
`DEBUG: Waiting for DeviceAgent to launch...`
`SHELL: /Users/{my_user_account}/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.4/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/{my_user_account}/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id 6523d786a05ebb78859c1930047ce46a09cb90a4`

When I checked `xcrun instruments -s devices` myself, I do see the physical device and its UDID that I'm referencing listed. 

Could it be that the iOSDeviceManager's `install` command skips the DeviceAgent-Runner installation if it's already installed, but it's not able to tell if it's already installed because of the `Error getting device with ID 6523d786a05ebb78859c1930047ce46a09cb90a4`?

Do you agree with Apple's recommendation and if so, is the best/easiest way to do this using the libimobiledevice solution that @otamas94 recommended in the comments above on Nov 7? I'll have to research how to implement this as that's new to me. 

Thanks again.

**Comment by jmoody** [comment]
> Could it be that the iOSDeviceManager's install command skips the DeviceAgent-Runner installation if it's already installed, but it's not able to tell if it's already installed because of the Error getting device with ID 6523d786a05ebb78859c1930047ce46a09cb90a4?

This is exactly what is happening.  iOSDeviceManager cannot connect to the device.

> libimobiledevice

That is what I am recommending to clients.  

If it is any consolation, I have seen reports of the same problem happening with Appium.

> does this snippet from the release notes not apply to my situation?

I believe it _does_ apply - both to iOS and macOS UI tests.  I am, however, primed to expect the worst from Apple with respect to it testing support.

**Comment by abardallis** [comment]
@jmoody This is very helpful. Really appreciate the clarifications and your time.

**Comment by jmoody** [comment]
I would _love_ to help more, but Calabash is not a priority for MSFT.

**Comment by blamay** [comment]
I'm still experiencing this issue only on iOS 11 devices.

@otamas94 How did you handle the lock screen after restarting the device?

**Comment by otamas94** [comment]
I put the phone into Airplane mode and, Insert a SIM card to avoid No SIM and such windows, and after restart I wait 60 second until the start of the next part of the test set.
