### ISSUE TITLE
Timed out waiting for UIAutomation run-loop

### ISSUE THREAD

**Issue by cliff76** [calabash/calabash-ios#874]
Hi,

I am trying to run calabash on a multi-project app with a workspace. I've managed to follow the online instructions, install bundler, build a simulator-cal build, run it, and verify the calabash server or something is bound to/listening on port 32765. I've added the following to my Gemfile to update bundler:

source 'https://rubygems.org'
gem 'run_loop', '>= 1.5.5', '< 2.0'
gem 'calabash-cucumber', '>= 0.16.3'

I've hard-coded the APP_BUNDLE_PATH for now until I can find a way to allow Calabash to find the app itself.
Still when I run cucumber with:

DEVICE_TARGET="iPhone 6 (9.0)" be cucumber

I get an error: "Timed out waiting for UIAutomation run-loop"

What am I missing?

**Comment by cliff76** [comment]
My output when using debug is as follows:

DEBUG=1 DEVICE_TARGET="iPhone 6 (9.0)" be cucumber
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError:

  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.

  Logfile: /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-12411-1jf9jrd/run_loop.out

  2015-10-12 14:03:10.059 instruments[13319:27261604] -[XRSimulatorDevice prepareConnection:]: Unable to authorize simulated daemon (13318): 5
  2015-10-12 14:03:20.221 instruments[13319:27261600] Failed to connect to local pid watcher service: (os/kern) failure
  2015-10-12 14:03:20.287 instruments[13319:27261641] Attempting to change event horizon while disengage
  Instruments Trace Error : Target failed to run: Permission to debug com.clifton.apps.MyApp was denied.
  2015-10-12 14:03:20.287 instruments[13319:27261742] Attempting to change event horizon while disengage


   (Calabash::Cucumber::Launcher::StartError)
  /Users/clifton/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:778:in `new_run_loop'
  /Users/clifton/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
  /Users/clifton/src/MyApp/features/support/01_launch.rb:28:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:217

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
3m34.103s
SFO1cliftonB:MyApp clifton$ DEBUG=1 DEVICE_TARGET="iPhone 6 (9.0)" be cucumber
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6

INFO: Using uia strategy: 'host'
DEBUG: Simulator instruction set 'x86_64' is compatible with '["x86_64"]'
DEBUG: Installed app is the same as #<APP: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app>
DEBUG: Launching #<Simulator: iPhone 6 (9.0) BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF
ERROR: execution expired
ERROR: execution expired
ERROR: execution expired
DEBUG: Simulator stable after 11.193172 seconds
DEBUG: Waited a total of 13.193172 seconds for simulator to stabilize
DEBUG: Took 13.373078 seconds to launch the simulator
2015-10-12 15:17:03 -0700 [RunLoop:debug]:
{
                        :app => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                  :bundle_id => "com.clifton.apps.MyApp",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.0)",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1",
          :results_dir_trace => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/trace",
                     :script => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.0)",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on iPhone 6 (9.0) App: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-12 15:17:09 -0700 [RunLoop:debug]: xcrun instruments -w BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF -D /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/trace -t Automation /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app -e UIARESULTSPATH /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1 -e UIASCRIPT /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/_run_loop.js >& /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1krxmk1/run_loop.out
2015-10-12 15:17:09 -0700 [RunLoop:debug]: Preparation took 21.256687 seconds
2015-10-12 15:17:39 -0700 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-10-12 15:17:39 -0700 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
DEBUG: Simulator instruction set 'x86_64' is compatible with '["x86_64"]'
DEBUG: Installed app is the same as #<APP: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app>
DEBUG: Launching #<Simulator: iPhone 6 (9.0) BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF
DEBUG: Simulator stable after 5.203393 seconds
DEBUG: Waited a total of 7.203393 seconds for simulator to stabilize
DEBUG: Took 7.328006 seconds to launch the simulator
2015-10-12 15:17:50 -0700 [RunLoop:debug]:
{
                        :app => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                  :bundle_id => "com.clifton.apps.MyApp",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.0)",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86",
          :results_dir_trace => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/trace",
                     :script => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.0)",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on iPhone 6 (9.0) App: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-12 15:17:51 -0700 [RunLoop:debug]: xcrun instruments -w BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF -D /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/trace -t Automation /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app -e UIARESULTSPATH /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86 -e UIASCRIPT /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/_run_loop.js >& /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-oufy86/run_loop.out
2015-10-12 15:17:51 -0700 [RunLoop:debug]: Preparation took 10.29952 seconds
2015-10-12 15:18:21 -0700 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-10-12 15:18:21 -0700 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
DEBUG: Simulator instruction set 'x86_64' is compatible with '["x86_64"]'
DEBUG: Installed app is the same as #<APP: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app>
DEBUG: Launching #<Simulator: iPhone 6 (9.0) BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF
DEBUG: Simulator stable after 5.047988 seconds
DEBUG: Waited a total of 7.047988 seconds for simulator to stabilize
DEBUG: Took 7.181397 seconds to launch the simulator
2015-10-12 15:18:31 -0700 [RunLoop:debug]:
{
                        :app => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                  :bundle_id => "com.clifton.apps.MyApp",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.0)",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws",
          :results_dir_trace => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/trace",
                     :script => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.0)",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on iPhone 6 (9.0) App: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-12 15:18:33 -0700 [RunLoop:debug]: xcrun instruments -w BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF -D /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/trace -t Automation /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app -e UIARESULTSPATH /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws -e UIASCRIPT /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/_run_loop.js >& /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-yh0pws/run_loop.out
2015-10-12 15:18:33 -0700 [RunLoop:debug]: Preparation took 10.170416 seconds
2015-10-12 15:19:03 -0700 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-10-12 15:19:03 -0700 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
DEBUG: Simulator instruction set 'x86_64' is compatible with '["x86_64"]'
DEBUG: Installed app is the same as #<APP: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app>
DEBUG: Launching #<Simulator: iPhone 6 (9.0) BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF
DEBUG: Simulator stable after 2.9894040000000004 seconds
DEBUG: Waited a total of 4.989404 seconds for simulator to stabilize
DEBUG: Took 5.118261 seconds to launch the simulator
2015-10-12 15:19:11 -0700 [RunLoop:debug]:
{
                        :app => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                  :bundle_id => "com.clifton.apps.MyApp",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.0)",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk",
          :results_dir_trace => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/trace",
                     :script => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.0)",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on iPhone 6 (9.0) App: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-12 15:19:13 -0700 [RunLoop:debug]: xcrun instruments -w BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF -D /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/trace -t Automation /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app -e UIARESULTSPATH /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk -e UIASCRIPT /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/_run_loop.js >& /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1w454zk/run_loop.out
2015-10-12 15:19:13 -0700 [RunLoop:debug]: Preparation took 8.445946 seconds
2015-10-12 15:19:43 -0700 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-10-12 15:19:43 -0700 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
DEBUG: Simulator instruction set 'x86_64' is compatible with '["x86_64"]'
DEBUG: Installed app is the same as #<APP: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app>
DEBUG: Launching #<Simulator: iPhone 6 (9.0) BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF
DEBUG: Simulator stable after 5.232218 seconds
DEBUG: Waited a total of 7.232218 seconds for simulator to stabilize
DEBUG: Took 7.363864 seconds to launch the simulator
2015-10-12 15:19:53 -0700 [RunLoop:debug]:
{
                        :app => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app",
                  :bundle_id => "com.clifton.apps.MyApp",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.0)",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q",
          :results_dir_trace => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/trace",
                     :script => "/var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.0)",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on iPhone 6 (9.0) App: /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app ###
EXEC: xcrun instruments -s devices
2015-10-12 15:19:55 -0700 [RunLoop:debug]: xcrun instruments -w BC62F91B-E2BA-47A6-AE39-D541ED1C5BBF -D /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/trace -t Automation /Users/clifton/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/MyApp-cal.app -e UIARESULTSPATH /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q -e UIASCRIPT /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/_run_loop.js >& /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/run_loop.out
2015-10-12 15:19:55 -0700 [RunLoop:debug]: Preparation took 10.423125 seconds
2015-10-12 15:20:25 -0700 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-10-12 15:20:25 -0700 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError:

  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.

  Logfile: /var/folders/wj/wwvtxhm52nd1xs3vxy3t24tdk7llgb/T/run_loop20151012-13927-1suvr2q/run_loop.out

  2015-10-12 15:19:55.936 instruments[14848:27330530] -[XRSimulatorDevice prepareConnection:]: Unable to authorize simulated daemon (14847): 5
  2015-10-12 15:20:06.101 instruments[14848:27330512] Failed to connect to local pid watcher service: (os/kern) failure
  2015-10-12 15:20:06.170 instruments[14848:27331758] Attempting to change event horizon while disengage
  Instruments Trace Error : Target failed to run: Permission to debug com.clifton.apps.MyApp was denied.
  2015-10-12 15:20:06.171 instruments[14848:27331758] Attempting to change event horizon while disengage


   (Calabash::Cucumber::Launcher::StartError)
  /Users/clifton/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:778:in `new_run_loop'
  /Users/clifton/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
  /Users/clifton/src/MyApp/features/support/01_launch.rb:28:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:217

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
3m39.162s

**Comment by jmoody** [comment]
@cliff76 Please reformat your question using GitHub code blocks - I can't read this as it is.

Does your project contain a Watch extension and did you use `calabash setup`?  If so you are experiencing this problem:

**Calabash builds/runs Apple Watch app instead of iPhone app** #832

**Comment by cliff76** [comment]
@jmoody I've formatted the console output using code blocks. No I am not using a watch extension. I used `be calabash setup` to setup my project.

**Comment by jmoody** [comment]
@cliff76 Thanks for the formatting!  Much easier to read.

> Does your project contain a Watch extension and did you use calabash setup? If so you are experiencing this problem:

Let's try to get to the bottom of this.  Can you do the following:

```
1. Find the .app you are trying test
2. Run this command:

$ xcrun strings "/path/to/Your.app/<Executable>" | grep -E 'CALABASH VERSION'

where < Executable > is the actual executable of the app, usually the same name of the app (with no extension).
```

If you don't see `0.16.4`, then the setup failed and failed in a way I have not seen yet.  

Many people are reporting the same or similar problems.  I'd like to get the bottom of this and soon.

**Comment by cliff76** [comment]
Sorry it's taken so long to respond. When I run the command I see:
CALABASH VERSION: 0.16.4

**Comment by jmoody** [comment]
@jfrndz @janemckay @cliff76 

Can one or all of you send me your app built for the iOS Simulator?  Contact me privately.

I want to get to the bottom of this and fast.

**Comment by cliff76** [comment]
Unfortunately I cannot share my app unless you sign an NDA. I tried to reproduce with a simpler app but could not. I then deleted everything generated, my features folder and all generated files, performed a git reset then started fresh again and everything worked! The last few times I did this I noticed the -cal target still existed even after doing a git reset of my project files so this time I manually deleted the "-cal" target. My best guess as to what happened was some old corrupt file was throwing things off. I originally tried running calabash without bundler which may have caused corruption during setup.I believe my manually deleting the -cal target got rid of the corruption. The documentation from the site does not direct one to start with bundler and the latest version of Bundler and run_loop.

**Comment by jmoody** [comment]
>  bundler and the latest version of Bundler and run_loop.

I am working on a documentation rewrite - including the README.md

**Comment by tsantos-resilient** [comment]
Hi, I think I'm having the same problem.
Calabash: 0.16.4
My project has two apps it runs ok when running the first app, but when gets to the feature where needs to run a second app the simulator lunches but the app doesn't gets installed and ends failing.
This used to run ok, start happening when I updated to Xcode 7.1 (previous using Xcode 6.4).

 @5257.setup
  Scenario: feature setup                                                                               # features/iPhone/test_display_phone_contact_list.feature:7
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
    Given that the address book is populated with the 'Display Phone Contact List @Story-5257' contacts # features/step_definitions/display_phone_contact_list_steps.rb:1
      Calabash::Cucumber::Launcher::StartError: 
      
      "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
      
      Logfile: /Users/Shared/Jenkins/.run-loop/results/2015-11-11_16-01-33/run_loop.out
      
      2015-11-11 16:01:49.272 instruments[76572:372114] Attempting to change event horizon while disengage
      Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.) : Failed to launch process with bundle identifier 'com.DummyContacts-cal'
      2015-11-11 16:01:49.273 instruments[76572:372113] Attempting to change event horizon while disengage
      
      
       (Calabash::Cucumber::Launcher::StartError)
      ./features/step_definitions/common_steps.rb:10:in `switch_to_dummy_contacts_app'
      ./features/step_definitions/display_phone_contact_list_steps.rb:2:in `/^that the address book is populated with the 'Display Phone Contact List ((?:.*))' contacts$/'
      features/iPhone/test_display_phone_contact_list.feature:8:in `Given that the address book is populated with the 'Display Phone Contact List @Story-5257' contacts'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (localhost:37265))
Failing... Errno::ECONNREFUSED
      Connection refused - connect(2) (localhost:37265) (Errno::ECONNREFUSED)
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:596:in `initialize'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:596:in `new'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:596:in `create_socket'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:741:in `block in connect'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:734:in `connect'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:496:in `query'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:169:in `query'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:1223:in `do_get_block'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:1006:in `block in do_request'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:1114:in `protect_keep_alive_disconnected'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:1001:in `do_request'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:843:in `request'
      /Users/Shared/Jenkins/.gem/gems/httpclient-2.7.0.1/lib/httpclient.rb:746:in `post'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/http_helpers.rb:57:in `block in make_http_request'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/http_helpers.rb:50:in `times'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/http_helpers.rb:29:in `http'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/map.rb:79:in `raw_map'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/map.rb:53:in `map'
      /Users/Shared/Jenkins/.gem/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/core.rb:112:in `query'
      /Users/Shared/Jenkins/Home/jobs/smartnumbersmobile-ios-dev/workspace/SmartNumbers/features/support/01_launch.rb:115:in `After'

**Comment by jmoody** [comment]
0.17.0 will allow users to opt into the :preferences strategy which will make the FIFO issue go away.

**Comment by nemesis** [comment]
@jmoody how should we exactly do that?

**Comment by jmoody** [comment]
```
launcher.relaunch({:launch_retries => 2, :uia_strategy => :preferences})
```

That is the only way.

**Comment by nemesis** [comment]
Sadly that did not resolve the issue. The tests run perfectly if launched on the CI machine from the command line or an ssh session, but they do not start smoothly and fail with errors like those shown by @tsantos-resilient. By the way, in a CI build, the app is launched and crashes instantly afterwards and causes UIAutomation timeouts, but I can launch the app by clicking on it in the simulator. What I might have missed?

**Comment by jmoody** [comment]
@nemesis And you are using 0.17.0?

**Comment by nemesis** [comment]
@jmoody Absolutely!

**Comment by jmoody** [comment]
What do the simulator logs say?   You might be able to tail the simulator log using:

```
# Open the simulator you are testing on
$ run-loop simctl tail

# In another shell, try to reproduce the crash
```

And what version of Xcode?

**Comment by jmoody** [comment]
It might be easier to move this discussion over to Gitter in the calabash/calabash0x channel.  We are evaluating Gitter as a communication tool.

**Comment by jmoody** [comment]
The issue @nemesis was experiencing has been resolved.

@cliff76 Are you you still seeing this issue?  If so, I invite you over to the Gitter chat?

Have you updated to 0.17.0 and tried the :preferences strategy?

**Comment by Aswini999** [comment]
Hi All... I'm facing the same issue.

```
2016-01-25 15:04:45 +0530 [RunLoop:debug]: Preparation took 2.503593 seconds
2016-01-25 15:05:15 +0530 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2016-01-25 15:05:15 +0530 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: 

"Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
```

Details:
Calabash-cucumber -0.17.1
run_loop -2.0.4
ruby 2.2.1
xcode-7.2
Device-version- iOS 9.1
MAC version: OS X EI Capitan 10.11.2 

Kindly Suggest

**Comment by czaku** [comment]
Same issue here.

run_loop 2.0.8
calabash-cucumber 0.18.1

**Comment by jmoody** [comment]
I have no concrete solution for this.

If this is a physical device, follow the guides in the [Hot Topics](https://github.com/calabash/calabash-ios/wiki/Hot-Topics).  Sadly, devices get into a bad state - especially after an iOS update.  There is no magic wand; you have to follow the debugging steps in the Hot Topics.  Even I have to do this.

If this an iOS Simulator, reboot your machine - the CoreSimulator environment is probably in a bad state.

I am happy to help anyone in a remote debugging session via tmate.

Ping me on [Gitter](https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by czaku** [comment]
@jmoody it is a simulator run.

It all runs fine on my local MacBook.

The issues happened when run through Bitrise (www.bitrise.io). I am using the exactly same script as I am running locally. 

I have tried investigating with Bitrise guys, but we are stuck.

Any help appreciated.

**Comment by jmoody** [comment]
> bitrise

You might be interested in these scripts that we use on Travis:

https://github.com/calabash/run_loop/blob/develop/scripts/ci/travis/instruments-auth.sh

In general, I try to avoid providing support for CI systems because they are notoriously finicky - especially if they are using VMs.  We test on Travis and Jenkins.

**Comment by jmoody** [comment]
I have released 2.0.10.pre1 which might resolve the FIFO problems.  Thanks @TeresaP

**Comment by SrinivasanTarget** [comment]
I'm still facing this issue on 0.19.1 and run_loop latest version.

```
"Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
```

Xcode: 7.3.1 and iOS: 9.2..Do we have any solution for this?

**Comment by SrinivasanTarget** [comment]
Hot Topics doesn't help me out as everything seems to be fine from my end as per the hot topic suggestions.

**Comment by mmorrisseymm** [comment]
We were getting this on our Jenkins server and even reached out to Apple to understand why instrument couldn't be controlled from the CLI (ran the XCinstruments test in this thread) ... They told us they no longer support the CLI for instruments so we continued troubleshooting. 

Although this isn't a fix, the workaround we discovered was to create another user on the device and re-install calabash with the new user and it has worked like a charm ever since.

We didn't take the time to understand why one user worked and the other didn't, but hope this helps folks in the interim get calabashing again.

**Comment by shravanjnaidu** [comment]
I had the same problem today. In my case, I was setting device_target, bundle_id, device_endpoint and app_path. Turns out if you're running your tests on a physical device(like me), you don't have to set the app_path. Which makes total sense. I was like duh to myself.

**Comment by tonylab** [comment]
I had the same problem for the past few days. Now got it fixed solution is the following listed below.

1)BUNDLE_ID associated with the xcode is the correct one also point to the -cal target 
2)DEVICE_TARGET go via xcode / windows / Devices, browse the device information and select the Device Identifier copy the UDID 
3)DEVICE_ENDPOINT build the app via xcode and target the build for your device. 

See below 

2016-08-02 16:09:47.838 DEBUG CalabashServer:242 | Creating the server: <LPHTTPServer: 0x1565ab20>
2016-08-02 16:09:47.839 DEBUG CalabashServer:243 | Calabash iOS server version: CALABASH VERSION: 0.19.2
2016-08-02 16:09:47.839 DEBUG CalabashServer:246 | App Base SDK: iphoneos9.3
2016-08-02 16:09:47.839 DEBUG CalabashServer:278 | IPHONE_SIMULATOR_ROOT: (null)
2016-08-02 16:09:47.867 DEBUG CalabashServer:264 | Calabash iOS server is listening on: **10.0.71.69 port 37265**
2016-08-02 16:09:48.787 DEBUG LPWKWebViewRuntimeLoader:192 | WKWebView is not available

The 10.0.71.69 port 37265 highlighted in bold is the information need for the endpoint, please note the IP address is not static so it might change from day to day so just be aware :)

4) Run Bundle exec cucumber -v 

Then it should work :) 

Good luck all.

**Comment by chalcrow** [comment]
You could try setting the WAIT_TIMEOUT environment variable before you specify the DEVICE_TARGET, so your line that runs cucumber will then read something like:

WAIT_TIMEOUT=90 DEVICE_TARGET="iPhone 6 (9.0)" be cucumber

This will change the default wait timeout from 30 seconds if your simulator is just slow. See http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-WAIT_TIMEOUT
